/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clinicamer.procedimiento;

import com.clinicamer.logica.Combo;
import com.clinicamer.logica.Historia;
import com.clinicamer.logica.HistoriaMed;
import static com.clinicamer.procedimiento.frmCHistoriaEnf.logica;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Bermudez
 */
public class frmCHistoriaMed extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCHistoriaMed
     */
    public frmCHistoriaMed() throws Exception {
        initComponents();
        this.llenarcboHistoria();
    }
    
    public void llenarcboHistoria() throws NoSuchAlgorithmException, Exception {
        cboHis.removeAllItems();
        try {
            List<Historia> l = new LinkedList<Historia>();
            l = logica.listarTodosHistoria();
            for (int i = 0; i < l.size(); i++) {
                cboHis.addItem(new Combo(l.get(i).getIdhistoria(), logica.consultarPacienteId(l.get(i).getIdpaciente()).getNombre() + " " + logica.consultarPacienteId(l.get(i).getIdpaciente()).getApellido()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmCirugia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmCirugia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboHis = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        btnCer = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblBusqEnf = new javax.swing.JTable();

        jLabel1.setText("Historia");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLim.setText("Limpiar");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });

        btnCer.setText("Cerrar");
        btnCer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel.setText("Resultado");

        jtblBusqEnf = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtblBusqEnf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblBusqEnf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblBusqEnfMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblBusqEnf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(193, 193, 193)
                                    .addComponent(jLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnEnviar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLim)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCer)))
                            .addGap(0, 124, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboHis, 0, 326, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEnviar)
                        .addComponent(btnLim)
                        .addComponent(btnCer))
                    .addGap(25, 25, 25)
                    .addComponent(jLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        List l = new LinkedList();

        try {
            l.clear(); // limpiamos el listado
            l = logica.consultarHistoriaMed( cboHis.getItemAt(cboHis.getSelectedIndex()).getIdCombo() );
            //System.out.println("lista " + l.size());
            DefaultTableModel modelo = new DefaultTableModel();
            jtblBusqEnf.setModel(modelo);
            modelo.addColumn("Historia Clinica");
            modelo.addColumn("Enfermedad");

            jLabel.setText("Resultado (" + l.size() + ")");
            Object[] fila = null;
            for (int i = 0; i < l.size(); i++) {
                modelo.addRow(fila);
                // Se crea un array que será una de las filas de la tabla.
                HistoriaMed hm = (HistoriaMed) l.get(i);
                //fila[i] = l.get(i);
                modelo.setValueAt(hm.getIdhistoria(), i, 0);
                modelo.setValueAt( logica.consultarMedicamentoId( hm.getIdmedicamento() ).getNombre(), i, 1);
            }
        } catch (Exception ex) {
            Logger.getLogger(frmCHistoriaMed.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimActionPerformed

    private void btnCerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerActionPerformed
        // TODO add your handling code here:
        this.dispose(); // cerrar ventana
    }//GEN-LAST:event_btnCerActionPerformed

    private void jtblBusqEnfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblBusqEnfMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtblBusqEnfMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCer;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLim;
    public javax.swing.JComboBox<Combo> cboHis;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblBusqEnf;
    // End of variables declaration//GEN-END:variables
}
