/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clinicamer.procedimiento;

import static clinicamer.principal.jDesktopPane;
import com.clinciamer.maestro.frmEnfermedad;
import com.clinicamer.consulta.frmConsulta;
import com.clinicamer.dao.Metodos;
import com.clinicamer.logica.Combo;
import com.clinicamer.logica.Historia;
import com.clinicamer.logica.Medico;
import com.clinicamer.logica.Paciente;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Bermudez
 */
public class frmHistoria extends javax.swing.JInternalFrame {
    
    // variables para gestionar los metodos a la base de datos HUELLAS
    static Metodos logica = new Metodos();
    
    /**
     * Creates new form frmHistoria
     */
    public frmHistoria() throws Exception {
        initComponents();
        this.llenarcboPaciente();
    }
    
    public void llenarcboPaciente() throws NoSuchAlgorithmException, Exception {
        cboPac.removeAllItems();
        try {
            List<Paciente> l = new LinkedList<Paciente>();
            l = logica.listarPacienteNombre();
            for (int i = 0; i < l.size(); i++) {
                cboPac.addItem(new Combo(l.get(i).getIdpaciente(), l.get(i).getNombre() + " " + l.get(i).getApellido()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateFe = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtDiag = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTrat = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnCan = new javax.swing.JButton();
        cboPac = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAnt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHab = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnVerMed = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnAddEnf = new javax.swing.JButton();
        btnVerEnf = new javax.swing.JButton();
        btnAddMed = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        setTitle("Historia");

        jLabel1.setText("Paciente");

        jLabel4.setText("Fecha");

        jDateFe.setDateFormatString("yyyy/MM/dd");

        jLabel3.setText("Observacion");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        jLabel5.setText("Diagnostico");

        jLabel6.setText("Tratamiento");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnCan.setText("Cerrar");
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("Alergias");

        jLabel7.setText("Antecedente");

        jLabel10.setText("Habitos");

        jLabel11.setText("Medicamento");
        jLabel11.setEnabled(false);

        btnVerMed.setText("Ver");
        btnVerMed.setEnabled(false);
        btnVerMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMedActionPerformed(evt);
            }
        });

        jLabel12.setText("Enfemedad");
        jLabel12.setEnabled(false);

        btnAddEnf.setText("...");
        btnAddEnf.setEnabled(false);
        btnAddEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEnfActionPerformed(evt);
            }
        });

        btnVerEnf.setText("Ver");
        btnVerEnf.setEnabled(false);
        btnVerEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEnfActionPerformed(evt);
            }
        });

        btnAddMed.setText("...");
        btnAddMed.setEnabled(false);
        btnAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrat, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHab, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addGap(12, 12, 12)
                                .addComponent(btnCan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVerEnf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVerMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnAddEnf)
                    .addComponent(btnVerEnf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnVerMed)
                    .addComponent(btnAddMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnModificar)
                    .addComponent(btnCan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        try {
            Historia h = new Historia();

            h.setIdpaciente(cboPac.getItemAt(cboPac.getSelectedIndex()).getIdCombo());
            h.setFehistoria(new java.sql.Date(jDateFe.getDate().getTime()) );
            h.setObservacion(txtObs.getText());
            h.setDiagnostico(txtDiag.getText());
            h.setTratamiento(txtTrat.getText());
            h.setAlergias(txtAle.getText());
            h.setAntecedentes(txtAnt.getText());
            h.setHabitos(txtHab.getText());
            System.out.println("historia "+h.toString());
            if (!logica.existeHistoria(logica.consultarPacienteId(h.getIdpaciente()).getNumeroDoc() )) {
                logica.guardarHistoria(h);
                JOptionPane.showMessageDialog(this, "Historia Clinica agregado correctamente", "Historia", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Historia Clinica existe", "Historia", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            Historia h = new Historia();

            h.setIdpaciente(cboPac.getItemAt(cboPac.getSelectedIndex()).getIdCombo());
            h.setFehistoria((Date) jDateFe.getDate());
            h.setObservacion(txtObs.getText());
            h.setDiagnostico(txtDiag.getText());
            h.setTratamiento(txtTrat.getText());
            h.setAlergias(txtAle.getText());
            h.setAntecedentes(txtAnt.getText());
            h.setHabitos(txtHab.getText());
            
            logica.modificarHistoria(h);
            JOptionPane.showMessageDialog(this, "Historia modificada correctamente", "Historia", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateException ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
        // TODO add your handling code here:
         this.dispose(); // cerrar ventana
    }//GEN-LAST:event_btnCanActionPerformed

    private void btnVerMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMedActionPerformed
        // TODO add your handling code here:
        try {
            frmCHistoriaMed frmCHistoriaMed = new frmCHistoriaMed();
            int x = (jDesktopPane.getWidth() / 2) - frmCHistoriaMed.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmCHistoriaMed.getHeight() / 2;
            frmCHistoriaMed.setLocation(x, y);
            jDesktopPane.add(frmCHistoriaMed);
            frmCHistoriaMed.show();
        } catch (Exception ex) {
            Logger.getLogger(frmCHistoriaEnf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerMedActionPerformed

    private void btnAddEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEnfActionPerformed
        // TODO add your handling code here:
        // agregar enfermedad
        try {
            frmHistoriaEnf frmHistoriaEnf = new frmHistoriaEnf();
            int x = (jDesktopPane.getWidth() / 2) - frmHistoriaEnf.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmHistoriaEnf.getHeight() / 2;
            frmHistoriaEnf.setLocation(x, y);
            jDesktopPane.add(frmHistoriaEnf);
            frmHistoriaEnf.show();
        } catch (Exception ex) {
            Logger.getLogger(frmHistoriaEnf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddEnfActionPerformed

    private void btnVerEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEnfActionPerformed
        // TODO add your handling code here:
        try {
            frmCHistoriaEnf frmCHistoriaEnf = new frmCHistoriaEnf();
            int x = (jDesktopPane.getWidth() / 2) - frmCHistoriaEnf.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmCHistoriaEnf.getHeight() / 2;
            frmCHistoriaEnf.setLocation(x, y);
            jDesktopPane.add(frmCHistoriaEnf);
            frmCHistoriaEnf.show();
        } catch (Exception ex) {
            Logger.getLogger(frmCHistoriaEnf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerEnfActionPerformed

    private void btnAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedActionPerformed
        // TODO add your handling code here:
        // agregar medicamentos
        try {
            frmHistoriaMed frmHistoriaMed = new frmHistoriaMed();
            int x = (jDesktopPane.getWidth() / 2) - frmHistoriaMed.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmHistoriaMed.getHeight() / 2;
            frmHistoriaMed.setLocation(x, y);
            jDesktopPane.add(frmHistoriaMed);
            frmHistoriaMed.show();
        } catch (Exception ex) {
            Logger.getLogger(frmHistoriaEnf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddMedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddEnf;
    public javax.swing.JButton btnAddMed;
    private javax.swing.JButton btnCan;
    public javax.swing.JButton btnEnviar;
    public static javax.swing.JButton btnModificar;
    public javax.swing.JButton btnVerEnf;
    public javax.swing.JButton btnVerMed;
    public javax.swing.JComboBox<Combo> cboPac;
    public com.toedter.calendar.JDateChooser jDateFe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAle;
    private javax.swing.JTextField txtAnt;
    public javax.swing.JTextField txtDiag;
    private javax.swing.JTextField txtHab;
    public javax.swing.JTextArea txtObs;
    public javax.swing.JTextField txtTrat;
    // End of variables declaration//GEN-END:variables
}
