/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicamer;

import com.clinciamer.maestro.frmConsultaUsuario;
import com.clinciamer.maestro.frmConsultarEnfermedad;
import com.clinciamer.maestro.frmEnfermedad;
import com.clinciamer.maestro.frmUsuario;
import com.clinicamer.consulta.frmConsulta;
import com.clinicamer.consulta.frmConsultaCita;
import com.clinicamer.dao.Conn;
import com.clinicamer.dao.Metodos;
import com.clinicamer.logica.Consulta;
import com.clinicamer.medico.frmConsutaMedico;
import com.clinicamer.medico.frmMedico;
import com.clinicamer.paciente.frmConsutaPaciente;
import com.clinicamer.paciente.frmPaciente;
import com.clinicamer.procedimiento.frmCirugia;
import com.clinicamer.procedimiento.frmConsultaCirugia;
import com.clinicamer.procedimiento.frmConsultaHistoria;
import com.clinicamer.procedimiento.frmConsultarIncapacidad;
import com.clinicamer.procedimiento.frmConsultarMedicamento;
import com.clinicamer.procedimiento.frmHistoria;
import com.clinicamer.procedimiento.frmIncapacidad;
import com.clinicamer.procedimiento.frmMedicamento;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jorge Bermudez
 */
public class principal extends javax.swing.JFrame {

    // variables para gestionar los metodos a la base de datos HUELLAS
    static Metodos logica = new Metodos();
    private Conn conn = new Conn();

    /**
     * Creates new form principal
     */
    public principal() throws IOException, NoSuchAlgorithmException, Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        this.consultarCitas();
    }

    public void consultarCitas() throws IOException, IllegalStateException, NoSuchAlgorithmException, Exception {
        List l = new LinkedList();
        l.clear(); // limpiamos el listado
        l = logica.listarTodosCitas();

        DefaultTableModel modelo = new DefaultTableModel();
        jtblListadoConsultas.setModel(modelo);
        modelo.addColumn("Nro Cita");
        modelo.addColumn("Paciente");
        modelo.addColumn("Medico");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Fecha");
        modelo.addColumn("Estado");
        //jLabel3.setText("Resultado (" + l.size() + ")");
        Object[] fila = null;
        for (int i = 0; i < l.size(); i++) {
            modelo.addRow(fila);
            // Se crea un array que será una de las filas de la tabla.
            Consulta c = (Consulta) l.get(i);
            System.out.println("consulta " + c.toString());
            //fila[i] = l.get(i);
            modelo.setValueAt(c.getIdconsulta(), i, 0);
            modelo.setValueAt(logica.consultarPacienteId(c.getIdpaciente()).getNombre() + " " + logica.consultarPacienteId(c.getIdpaciente()).getApellido(), i, 1);
            modelo.setValueAt(logica.consultarMedicoId(c.getIdmedico()).getNombre() + " " + logica.consultarMedicoId(c.getIdmedico()).getApellido(), i, 2);
            modelo.setValueAt(c.getEspecialidad(), i, 3);
            modelo.setValueAt(c.getFeconsulta(), i, 4);
            modelo.setValueAt(c.getEstado(), i, 5);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListadoConsultas = new javax.swing.JTable();
        btnAct = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClinicaMER");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Listado de Citas Medicas");

        jtblListadoConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblListadoConsultas);

        btnAct.setText("Actualizar");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnAct)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Pacientes");

        jMenuItem1.setText("Agregar paciente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem8.setText("Consulta Paciente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Medicos");

        jMenuItem2.setText("Agregar medico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem10.setText("Consultar Medico");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Gestion");

        jMenuItem3.setText("Agregar Cita");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem11.setText("Consulta Cita");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem13.setText("Agregar Historia Clinica");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("Consultar Historia Clinica");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Procedimiento");

        jMenuItem4.setText("Agregar Cirugia");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Consultar Cirugia");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Agregar Incapacidad");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem12.setText("Consultar Incapacidad");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Informes");

        jMenuItem20.setText("Informe de pacientes");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuItem21.setText("Informe de citas medicas");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem21);

        jMenuItem22.setText("Informes de medicos");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuBar1.add(jMenu8);

        jMenu6.setText("Maestro");

        jMenuItem7.setText("Agregar Usuario");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem17.setText("Consultar Usuario");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem17);

        jMenuItem18.setText("Agregar Enfermedad");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem19.setText("Consultar Enfermedad");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem19);

        jMenuItem15.setText("Agregar Medicamento");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenuItem16.setText("Consultar Medicamento");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            frmPaciente frmPaciente = new frmPaciente();
            int x = (jDesktopPane.getWidth() / 2) - frmPaciente.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmPaciente.getHeight() / 2;
            frmPaciente.setLocation(x, y);
            jDesktopPane.add(frmPaciente);
            frmPaciente.show();
        } catch (Exception ex) {
            Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsutaPaciente frmConsutaPaciente = new frmConsutaPaciente();
            int x = (jDesktopPane.getWidth() / 2) - frmConsutaPaciente.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsutaPaciente.getHeight() / 2;
            frmConsutaPaciente.setLocation(x, y);
            jDesktopPane.add(frmConsutaPaciente);
            frmConsutaPaciente.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsutaPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            frmMedico frmMedico = new frmMedico();
            int x = (jDesktopPane.getWidth() / 2) - frmMedico.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmMedico.getHeight() / 2;
            frmMedico.setLocation(x, y);
            jDesktopPane.add(frmMedico);
            frmMedico.show();
        } catch (Exception ex) {
            Logger.getLogger(frmMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsutaMedico frmConsutaMedico = new frmConsutaMedico();
            int x = (jDesktopPane.getWidth() / 2) - frmConsutaMedico.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsutaMedico.getHeight() / 2;
            frmConsutaMedico.setLocation(x, y);
            jDesktopPane.add(frmConsutaMedico);
            frmConsutaMedico.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsutaMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsulta frmConsulta = new frmConsulta();
            int x = (jDesktopPane.getWidth() / 2) - frmConsulta.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsulta.getHeight() / 2;
            frmConsulta.setLocation(x, y);
            jDesktopPane.add(frmConsulta);
            frmConsulta.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsultaCita frmConsultaCita = new frmConsultaCita();
            int x = (jDesktopPane.getWidth() / 2) - frmConsultaCita.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsultaCita.getHeight() / 2;
            frmConsultaCita.setLocation(x, y);
            jDesktopPane.add(frmConsultaCita);
            frmConsultaCita.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsultaCita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        try {
            frmHistoria frmHistoria = new frmHistoria();
            int x = (jDesktopPane.getWidth() / 2) - frmHistoria.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmHistoria.getHeight() / 2;
            frmHistoria.setLocation(x, y);
            jDesktopPane.add(frmHistoria);
            frmHistoria.show();
        } catch (Exception ex) {
            Logger.getLogger(frmHistoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsultaHistoria frmConsultaHistoria = new frmConsultaHistoria();
            int x = (jDesktopPane.getWidth() / 2) - frmConsultaHistoria.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsultaHistoria.getHeight() / 2;
            frmConsultaHistoria.setLocation(x, y);
            jDesktopPane.add(frmConsultaHistoria);
            frmConsultaHistoria.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsultaHistoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try {
            frmUsuario frmUsuario = new frmUsuario();
            int x = (jDesktopPane.getWidth() / 2) - frmUsuario.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmUsuario.getHeight() / 2;
            frmUsuario.setLocation(x, y);
            jDesktopPane.add(frmUsuario);
            frmUsuario.show();
        } catch (Exception ex) {
            Logger.getLogger(frmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsultaUsuario frmConsultaUsuario = new frmConsultaUsuario();
            int x = (jDesktopPane.getWidth() / 2) - frmConsultaUsuario.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsultaUsuario.getHeight() / 2;
            frmConsultaUsuario.setLocation(x, y);
            jDesktopPane.add(frmConsultaUsuario);
            frmConsultaUsuario.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsultaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        try {
            frmEnfermedad frmEnfermedad = new frmEnfermedad();
            int x = (jDesktopPane.getWidth() / 2) - frmEnfermedad.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmEnfermedad.getHeight() / 2;
            frmEnfermedad.setLocation(x, y);
            jDesktopPane.add(frmEnfermedad);
            frmEnfermedad.show();
        } catch (Exception ex) {
            Logger.getLogger(frmEnfermedad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsultarEnfermedad frmConsultarEnfermedad = new frmConsultarEnfermedad();
            int x = (jDesktopPane.getWidth() / 2) - frmConsultarEnfermedad.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsultarEnfermedad.getHeight() / 2;
            frmConsultarEnfermedad.setLocation(x, y);
            jDesktopPane.add(frmConsultarEnfermedad);
            frmConsultarEnfermedad.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsultarEnfermedad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            frmCirugia frmCirugia = new frmCirugia();
            int x = (jDesktopPane.getWidth() / 2) - frmCirugia.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmCirugia.getHeight() / 2;
            frmCirugia.setLocation(x, y);
            jDesktopPane.add(frmCirugia);
            frmCirugia.show();
        } catch (Exception ex) {
            Logger.getLogger(frmCirugia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        try {
            frmMedicamento frmMedicamento = new frmMedicamento();
            int x = (jDesktopPane.getWidth() / 2) - frmMedicamento.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmMedicamento.getHeight() / 2;
            frmMedicamento.setLocation(x, y);
            jDesktopPane.add(frmMedicamento);
            frmMedicamento.show();
        } catch (Exception ex) {
            Logger.getLogger(frmMedicamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsultarMedicamento frmConsultarMedicamento = new frmConsultarMedicamento();
            int x = (jDesktopPane.getWidth() / 2) - frmConsultarMedicamento.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsultarMedicamento.getHeight() / 2;
            frmConsultarMedicamento.setLocation(x, y);
            jDesktopPane.add(frmConsultarMedicamento);
            frmConsultarMedicamento.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsultarMedicamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try {
            frmIncapacidad frmIncapacidad = new frmIncapacidad();
            int x = (jDesktopPane.getWidth() / 2) - frmIncapacidad.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmIncapacidad.getHeight() / 2;
            frmIncapacidad.setLocation(x, y);
            jDesktopPane.add(frmIncapacidad);
            frmIncapacidad.show();
        } catch (Exception ex) {
            Logger.getLogger(frmIncapacidad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsultarIncapacidad frmConsultarIncapacidad = new frmConsultarIncapacidad();
            int x = (jDesktopPane.getWidth() / 2) - frmConsultarIncapacidad.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsultarIncapacidad.getHeight() / 2;
            frmConsultarIncapacidad.setLocation(x, y);
            jDesktopPane.add(frmConsultarIncapacidad);
            frmConsultarIncapacidad.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsultarIncapacidad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try {
            frmConsultaCirugia frmConsultaCirugia = new frmConsultaCirugia();
            int x = (jDesktopPane.getWidth() / 2) - frmConsultaCirugia.getWidth() / 2;
            int y = (jDesktopPane.getHeight() / 2) - frmConsultaCirugia.getHeight() / 2;
            frmConsultaCirugia
                    .setLocation(x, y);
            jDesktopPane.add(frmConsultaCirugia);
            frmConsultaCirugia.show();
        } catch (Exception ex) {
            Logger.getLogger(frmConsultaCirugia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        try {
            JasperReport jasperReport;
            Connection conexion;
            conexion = conn.Conectar(); // cargamos la conexion

            jasperReport = (JasperReport) JRLoader.loadObjectFromFile( "D:\\rpt_pacientes.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conexion);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("REPORTE DE PACIENTES");
            jasperViewer.setVisible(true);

        } catch (IllegalStateException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        try {
            JasperReport jasperReport;
            Connection conexion;
            conexion = conn.Conectar(); // cargamos la conexion

            jasperReport = (JasperReport) JRLoader.loadObjectFromFile( "D:\\rpt_consultas.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conexion);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("REPORTE DE CITAS MEDICAS");
            jasperViewer.setVisible(true);

        } catch (IllegalStateException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        try {
            JasperReport jasperReport;
            Connection conexion;
            conexion = conn.Conectar(); // cargamos la conexion

            jasperReport = (JasperReport) JRLoader.loadObjectFromFile( "D:\\rpt_medicos.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conexion);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("REPORTE DE MEDICOS");
            jasperViewer.setVisible(true);

        } catch (IllegalStateException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
        try {
            // TODO add your handling code here:
            this.consultarCitas();
        } catch (IllegalStateException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new principal().setVisible(true);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAct;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblListadoConsultas;
    // End of variables declaration//GEN-END:variables
}
